// Generates stock_lights.lua: every single light the Night Optimized build switches off, rebuilt as
// Lua lights that exist ONLY on Normal and No Dogbowls, at night (CSP NIGHT_SHARP: sun angle >= 88).
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex').slice(0,16);
const ORIG=path.join(__dirname,'ext_config.ORIGINAL.ini');
const NIGHT=process.argv[2]; const OUT=process.argv[3];
if(sha(fs.readFileSync(ORIG))!=='469a1733c2868b84'){console.error('REFUSING: original backup does not match');process.exit(1)}
const sections=f=>{const out=[];let cur=null;for(const raw of fs.readFileSync(f,'utf8').split(/\r?\n/)){const l=raw.trim();
  const m=l.match(/^\[([A-Z_]+?)(?:_(\.\.\.|\d+))?\]/);if(m){cur={type:m[1],kv:{}};out.push(cur);continue}
  if(!cur||!l||l.startsWith(';'))continue;const k=l.match(/^([A-Za-z_\.]+)\s*=\s*(.*?)\s*(;.*)?$/);if(k)cur.kv[k[1].toUpperCase()]=k[2]}return out};
const o=sections(ORIG).filter(s=>s.type==='LIGHT'||s.type==='LIGHT_SERIES'), n=sections(NIGHT).filter(s=>s.type==='LIGHT'||s.type==='LIGHT_SERIES');
if(o.length!==n.length){console.error('section count differs',o.length,n.length);process.exit(1)}
const off=s=>String(s.kv.ACTIVE).trim()==='0';
const move=[],skipped=[];o.forEach((s,i)=>{if(!off(s)&&off(n[i])){(s.type==='LIGHT'?move:skipped).push(s)}});
const num=v=>+v, v3=v=>v.split(',').map(Number), col=v=>{const c=v.split(',').map(Number);const m=c.length>3?c[3]:1;return [c[0]*m,c[1]*m,c[2]*m]};
const MAP={POSITION:['position',v3],DIRECTION:['direction',v3],RANGE:['range',num],RANGE_GRADIENT_OFFSET:['rangeGradientOffset',num],
 FADE_AT:['fadeAt',num],FADE_SMOOTH:['fadeSmooth',num],SPOT:['spot',num],SPOT_SHARPNESS:['spotSharpness',num],
 DIFFUSE_CONCENTRATION:['diffuseConcentration',num],SPECULAR_MULT:['specularMultiplier',num],SINGLE_FREQUENCY:['singleFrequency',num],
 VOLUMETRIC_LIGHT:['volumetricLight',v=>v.trim()==='1'],SHADOWS:['shadows',v=>v.trim()==='1'],SHADOWS_HALF_RESOLUTION:['shadowsHalfResolution',v=>v.trim()==='1'],
 SHADOWS_EXTRA_BLUR:['shadowsExtraBlur',v=>v.trim()==='1'],SHADOWS_BOOST:['shadowsBoost',num],SHADOWS_EXP_FACTOR:['shadowsExponentialFactor',num],
 COLOR:['color',col],LINE_FROM:['position',v3],LINE_TO:['linePos',v3],COLOR_FROM:['color',col],COLOR_TO:['lineColor',col]};
const IGNORE=new Set(['CONDITION','ACTIVE']);const unmapped={};
const lua=v=>Array.isArray(v)?`{${v.map(x=>+x.toFixed(6)).join(',')}}`:(typeof v==='boolean'?String(v):String(+(+v).toFixed(6)));
const rows=move.map(s=>{const f=[];if(s.kv.LINE_FROM)f.push('line=true');
  for(const [k,v] of Object.entries(s.kv)){if(IGNORE.has(k))continue;const m=MAP[k];if(!m){unmapped[k]=(unmapped[k]||0)+1;continue}f.push(`${m[0]}=${lua(m[1](v))}`)}
  if(s.kv.CONDITION&&s.kv.CONDITION.trim()!=='NIGHT_SHARP')unmapped['CONDITION='+s.kv.CONDITION]=1;return '  {'+f.join(', ')+'},'});
const src=`-- stock_lights.lua — the author's stadium, ambient and track-stadium lights, rebuilt as Lua lights.
-- GENERATED by make_variant_script.js from the author's original ext_config.ini (sha256 469a1733c2868b84…).
-- They exist on every layout EXCEPT '${'night_optimized'}', and only at night, using CSP's NIGHT_SHARP rule
-- (INPUT = SUN, on from a sun angle of 88°). The config itself carries only what is lit on every layout.
local NIGHT_OPTIMIZED = 'night_optimized'
local layout = ac.getTrackLayout()
if layout == NIGHT_OPTIMIZED then
  ac.log('[stock_lights] layout night_optimized: stadium and ambient lights stay off')
  return
end
local LIGHTS = {
${rows.join('\n')}
}
local function v(t) return vec3(t[1], t[2], t[3]) end
local function c(t) return rgb(t[1], t[2], t[3]) end
local live, on = {}, nil
local function build()
  for i, d in ipairs(LIGHTS) do
    local l = ac.LightSource(d.line and ac.LightType.Line or ac.LightType.Regular)
    for k, x in pairs(d) do
      if k == 'position' or k == 'direction' or k == 'linePos' then l[k] = v(x)
      elseif k == 'color' or k == 'lineColor' then l[k] = c(x)
      elseif k ~= 'line' then l[k] = x end
    end
    live[i] = l
  end
end
local function clear() for _, l in ipairs(live) do l:dispose() end live = {} end
ac.log('[stock_lights] loaded on layout "' .. layout .. '": ' .. #LIGHTS .. ' lights')
function script.update(dt)
  local night = ac.getSunAngle() >= 88
  if night ~= on then
    on = night
    if on then build() else clear() end
    ac.log(string.format('[stock_lights] sunAngle=%.2f sunPitch=%.2f -> %s, %d live', ac.getSunAngle(), ac.getSunPitchAngle(), on and 'ON' or 'OFF', #live))
  end
end
`;
fs.writeFileSync(OUT,src);
console.log('lights moved to Lua:',move.length,'| series left to the config (off everywhere):',skipped.length);
console.log('config keys with no Lua equivalent:',Object.keys(unmapped).length?JSON.stringify(unmapped):'none');
console.log('line lights:',move.filter(s=>s.kv.LINE_FROM).length);
